data<-read.table("household_power_consumption.txt",sep=";",header=TRUE,na.strings="?")
data$Date<-as.Date(data$Date,format='%d/%m/%Y')
dataFinal<-subset(data,Date%in%as.Date(c("2007-02-01","2007-02-02")))
dataFinal$datetime<-as.POSIXct(paste(dataFinal$Date,dataFinal$Time))
png("plot3.png", width=480, height=480)
plot(dataFinal$datetime,dataFinal$Sub_metering_1,xlab="",ylab="Energy sub metering",type="l")
lines(dataFinal$datetime,dataFinal$Sub_metering_2,col="red")
lines(dataFinal$datetime,dataFinal$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),lty=1,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()